version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pocuser
      POSTGRES_PASSWORD: pocpass
      POSTGRES_DB: pocdb
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
  backend:
    build: backend
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://pocuser:pocpass@db:5432/pocdb
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
  frontend:
    build: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data: